const { pathsToModuleNameMapper } = require('ts-jest');
const { compilerOptions } = require('./tsconfig.json');

module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  projects: [
    {
      displayName: 'unit',
      preset: 'ts-jest',
      testEnvironment: 'node',
      testMatch: ['<rootDir>/test/unit/**/*.spec.ts'],
      collectCoverageFrom: [
        'src/**/*.(t|j)s',
        '!src/**/*.spec.ts',
        '!src/**/*.interface.ts',
        '!src/**/index.ts',
        '!src/**/*.module.ts',
        '!src/main.ts',
        '!src/testing/**/*',
      ],
      coverageDirectory: './coverage/unit',
      coverageReporters: ['text', 'lcov', 'html'],
      moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, {
        prefix: '<rootDir>/',
      }),
      setupFilesAfterEnv: ['<rootDir>/test/setup.ts'],
      testTimeout: 10000,
    },
    {
      displayName: 'integration',
      preset: 'ts-jest',
      testEnvironment: 'node',
      testMatch: ['<rootDir>/test/integration/**/*.spec.ts'],
      collectCoverageFrom: [
        'src/**/*.(t|j)s',
        '!src/**/*.spec.ts',
        '!src/**/*.integration.spec.ts',
        '!src/**/*.interface.ts',
        '!src/**/index.ts',
        '!src/**/*.module.ts',
        '!src/main.ts',
        '!src/testing/**/*',
      ],
      coverageDirectory: './coverage/integration',
      coverageReporters: ['text', 'lcov', 'html'],
      moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, {
        prefix: '<rootDir>/',
      }),
      setupFilesAfterEnv: ['<rootDir>/test/integration-setup.ts'],
      testTimeout: 30000,
    },
    {
      displayName: 'e2e',
      preset: 'ts-jest',
      testEnvironment: 'node',
      testMatch: ['<rootDir>/test/**/*.e2e-spec.ts'],
      collectCoverageFrom: [
        'src/**/*.(t|j)s',
        '!src/**/*.spec.ts',
        '!src/**/*.integration.spec.ts',
        '!src/**/*.interface.ts',
        '!src/**/index.ts',
        '!src/**/*.module.ts',
        '!src/main.ts',
        '!src/testing/**/*',
      ],
      coverageDirectory: './coverage/e2e',
      coverageReporters: ['text', 'lcov', 'html'],
      moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, {
        prefix: '<rootDir>/',
      }),
      setupFilesAfterEnv: ['<rootDir>/test/e2e-setup.ts'],
      testTimeout: 60000,
    },
  ],
  collectCoverageFrom: [
    'src/**/*.(t|j)s',
    '!src/**/*.spec.ts',
    '!src/**/*.integration.spec.ts',
    '!src/**/*.interface.ts',
    '!src/**/index.ts',
    '!src/**/*.module.ts',
    '!src/main.ts',
    '!src/testing/**/*',
  ],
  coverageDirectory: './coverage/combined',
  coverageReporters: ['text', 'lcov', 'html'],
  coverageThreshold: {
    global: {
      branches: 85,
      functions: 85,
      lines: 85,
      statements: 85,
    },
    'src/domain/**/*.ts': {
      branches: 95,
      functions: 95,
      lines: 95,
      statements: 95,
    },
    'src/application/**/*.ts': {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90,
    },
  },
};
